name: Fetch Discord Messages

on:
  schedule:
    - cron: '* * * * *'  # 每天 UTC 时间的午夜触发

jobs:
  fetch-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Discord Fetch
      env:
        DISCORD_TOKEN: ${{ secrets.TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: node discord-fetch.js
